-- MySQL Script generated by MySQL Workbench
-- Thu Jan 29 10:31:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`concierto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`concierto` (
  `id_concierto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `artista` VARCHAR(100) NULL,
  `ciudad` VARCHAR(100) NULL,
  `cartel` VARCHAR(255) NULL,
  PRIMARY KEY (`id_concierto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesion` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `id_concierto` INT NOT NULL,
  `concierto_id_concierto` INT NOT NULL,
  PRIMARY KEY (`id_sesion`),
  INDEX `fk_sesion_concierto_idx` (`concierto_id_concierto` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_concierto`
    FOREIGN KEY (`concierto_id_concierto`)
    REFERENCES `mydb`.`concierto` (`id_concierto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona` (
  `id_zona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`butaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`butaca` (
  `id_butaca` INT NOT NULL AUTO_INCREMENT,
  `fila` VARCHAR(5) NOT NULL,
  `numero` INT NOT NULL,
  `id_zona` INT NOT NULL,
  `zona_id_zona` INT NOT NULL,
  PRIMARY KEY (`id_butaca`),
  INDEX `fk_butaca_zona1_idx` (`zona_id_zona` ASC) VISIBLE,
  CONSTRAINT `fk_butaca_zona1`
    FOREIGN KEY (`zona_id_zona`)
    REFERENCES `mydb`.`zona` (`id_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
